# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# I. Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: your-title-here
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Your description here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


# II. Build settings
# theme: mini

# plugins:
#   - jekyll-feed
#   - jekyll-sitemap

sass:
  style: compressed

# III. Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/




  # VI. Collections
  # add any collections you wish to create here. Can be in the form of an array or a hash
  # collections:
  # - array_format
  #
  # collections:
  # hash_format:
  #   metadata_here: true




  # V. Navigation
  # any pages that end up in the navbar will go here
  # navigation:
  # - title: Home
  #   url: /
  # - title: About
  #   url: /about

  # links for recurring buttons (like a subscribe button) should go here
  # button-nav: "Hello world"

  # VI. Social
  # Twitter: https://your_profile_link.com
  # LinkedIn: https://your_profile_link.com
  # Facebook: https://your_profile_link.com

